/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author rojal
 */
public class CategoryofMedicine extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryofMedicine.class.getName());

    /**
     * Creates new form CategoryofMedicine
     */
    public CategoryofMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(245, 253, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 100));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reallogo.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 40, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel2.setText("Pharm-Assist");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 0, 130, 28);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Your healthy dose of convenience");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 40, 172, 17);

        jButton1.setBackground(new java.awt.Color(14, 93, 174));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("All Categories");
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 80, 110, 23);

        jTextField1.setPreferredSize(new java.awt.Dimension(398, 34));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(170, 10, 370, 34);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchlogo.png"))); // NOI18N
        jPanel2.add(jButton2);
        jButton2.setBounds(540, 10, 30, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartlogo.png"))); // NOI18N
        jPanel2.add(jButton3);
        jButton3.setBounds(580, 10, 31, 32);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounticon.png"))); // NOI18N
        jPanel2.add(jButton4);
        jButton4.setBounds(620, 10, 30, 30);

        jLabel4.setText("Account");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(650, 20, 50, 16);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmiicon.png"))); // NOI18N
        jButton7.setText("BMI");
        jPanel2.add(jButton7);
        jButton7.setBounds(380, 70, 80, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emergencyicon.png"))); // NOI18N
        jButton6.setText("Emergency Contacts");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel2.add(jButton6);
        jButton6.setBounds(140, 70, 170, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactpharmacyicon.png"))); // NOI18N
        jButton8.setText("Contact Pharmacy");
        jPanel2.add(jButton8);
        jButton8.setBounds(540, 70, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 100);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(112, 317));
        jPanel3.setLayout(null);

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jButton9.setText("Pain Relief");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel3.add(jButton9);
        jButton9.setBounds(0, 20, 110, 26);

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jButton10.setText("Anti Fungal");
        jButton10.addActionListener(this::jButton10ActionPerformed);
        jPanel3.add(jButton10);
        jButton10.setBounds(0, 50, 110, 26);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 120, 112, 317);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(530, 317));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel5.setText("painkiller");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(160, 0, 50, 16);

        jLabel7.setText("jLabel7");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(70, 40, 38, 16);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 30, 530, 110);

        jPanel6.setLayout(null);

        jLabel6.setText("Antifungal");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(160, 0, 60, 16);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 160, 530, 120);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(140, 120, 530, 317);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
jPanel5.setVisible(true);
jPanel6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
jPanel5.setVisible(false);
jPanel6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoryofMedicine().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
