/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author This PC
 */


public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    private void initPopupMenu() {
        
}
private Controller.DashboardController controller;
private Controller.ShoppingCartController cartController;
private Controller.SearchController searchController;
private String currentCategory = "All";
private javax.swing.JLabel selectedPriceLabel = new javax.swing.JLabel("Rs. 0");
private javax.swing.JLabel totalPriceLabel = new javax.swing.JLabel("Rs. 0");



    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        SelectedPrice.setLayout(new java.awt.BorderLayout());
TotalPriceAdd.setLayout(new java.awt.BorderLayout());

SelectedPrice.add(selectedPriceLabel, java.awt.BorderLayout.CENTER);
TotalPriceAdd.add(totalPriceLabel, java.awt.BorderLayout.CENTER);
        
        controller = new Controller.DashboardController(this);
        searchController = new Controller.SearchController();
        
        cartController = new Controller.ShoppingCartController(this); 
        

// Select all
checkbox1.addItemListener(e -> cartController.selectAll(checkbox1.getState()));

// Delete selected
jButton1.addActionListener(e -> cartController.deleteSelected());

// Confirm cart
ConfirmPayment.addActionListener(e -> cartController.confirmCart());

// whenever cart page opens
jButton5.addActionListener(e -> {
    CardLayout card = (CardLayout) contentPanel.getLayout();
    card.show(contentPanel, "cart");
    cartController.refreshCart();
});

        initPopupMenu();
        loadProductUI();
        loadAllProducts();
        
        SearchButton.addActionListener(e -> performSearch()); 
    }

     private void loadProductUI() {
         
           
}
    private void loadAllProducts() {

    productListPanel.removeAll();
    productListPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

    try {
        java.util.List<Model.Product> products = controller.getAllProducts();
        for (Model.Product product : products) {
    ProductCard card = new ProductCard();
    card.setDashboard(this);          // 🔥 VERY IMPORTANT
    card.setProduct(product);
    card.setPreferredSize(new Dimension(150, 170));
    productListPanel.add(card);
}


    } catch (Exception e) {
        e.printStackTrace();
    }

    productListPanel.revalidate();
    productListPanel.repaint();
}
    private void loadProductsByCategory(String category) {
           productListPanel.removeAll();
    productListPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));

    try {
        java.util.List<Model.Product> products = controller.getProductsByCategory(category);


        for (Model.Product product : products) {
           ProductCard card = new ProductCard();
            card.setDashboard(this);          // ✅ VERY IMPORTANT
            card.setProduct(product);
            card.setPreferredSize(new Dimension(150, 170));
            productListPanel.add(card);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    productListPanel.revalidate();
    productListPanel.repaint();
        
        
        
    }
    
   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Profile = new javax.swing.JMenuItem();
        RateUs = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        Searchbar = new javax.swing.JTextField();
        Allcategoriesbtn = new javax.swing.JButton();
        Emergencycontactsbtn = new javax.swing.JButton();
        Bmibtn = new javax.swing.JButton();
        Contactpharmacybtn = new javax.swing.JButton();
        logopharmassist = new javax.swing.JLabel();
        Accountbtn = new javax.swing.JButton();
        namepharmassist = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        categories = new javax.swing.JPanel();
        categoryFilterPanel = new javax.swing.JPanel();
        PainReliefbtn = new javax.swing.JButton();
        AntiFungalbtn = new javax.swing.JButton();
        Allbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        productScrollPane = new javax.swing.JScrollPane();
        productListPanel = new javax.swing.JPanel();
        emergency = new javax.swing.JPanel();
        bmi = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        pharmacy = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ShoppingCart = new javax.swing.JPanel();
        Selected = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        OrderSummary = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SelectedPrice = new javax.swing.JPanel();
        TotalPriceAdd = new javax.swing.JPanel();
        ConfirmPayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        PictureOfMeds = new javax.swing.JPanel();
        NameOfMeds = new javax.swing.JPanel();
        Quantity = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        Subtract = new javax.swing.JButton();

        Profile.setText("Profile");
        jPopupMenu1.add(Profile);

        RateUs.setText("Rateus");
        jPopupMenu1.add(RateUs);

        Logout.setText("Logout");
        jPopupMenu1.add(Logout);

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");
        scrollPane1.add(jLabel1);

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchlogo.png"))); // NOI18N
        SearchButton.addActionListener(this::SearchButtonActionPerformed);
        jPanel1.add(SearchButton);
        SearchButton.setBounds(515, 10, 45, 30);

        Searchbar.addActionListener(this::SearchbarActionPerformed);
        jPanel1.add(Searchbar);
        Searchbar.setBounds(200, 10, 360, 30);

        Allcategoriesbtn.setBackground(new java.awt.Color(14, 94, 174));
        Allcategoriesbtn.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        Allcategoriesbtn.setForeground(new java.awt.Color(255, 255, 255));
        Allcategoriesbtn.setText("All Categories");
        Allcategoriesbtn.setBorder(null);
        Allcategoriesbtn.setBorderPainted(false);
        Allcategoriesbtn.addActionListener(this::AllcategoriesbtnActionPerformed);
        jPanel1.add(Allcategoriesbtn);
        Allcategoriesbtn.setBounds(0, 70, 122, 28);

        Emergencycontactsbtn.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        Emergencycontactsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emergencyicon.png"))); // NOI18N
        Emergencycontactsbtn.setText("Emergency Contacts  ");
        Emergencycontactsbtn.setBorder(null);
        Emergencycontactsbtn.setBorderPainted(false);
        Emergencycontactsbtn.setContentAreaFilled(false);
        Emergencycontactsbtn.addActionListener(this::EmergencycontactsbtnActionPerformed);
        jPanel1.add(Emergencycontactsbtn);
        Emergencycontactsbtn.setBounds(180, 70, 160, 28);

        Bmibtn.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        Bmibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmiicon.png"))); // NOI18N
        Bmibtn.setText("BMI");
        Bmibtn.setBorder(null);
        Bmibtn.setBorderPainted(false);
        Bmibtn.setContentAreaFilled(false);
        Bmibtn.addActionListener(this::BmibtnActionPerformed);
        jPanel1.add(Bmibtn);
        Bmibtn.setBounds(410, 70, 60, 28);

        Contactpharmacybtn.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        Contactpharmacybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactpharmacyicon.png"))); // NOI18N
        Contactpharmacybtn.setText("Contact Pharmacy");
        Contactpharmacybtn.setBorder(null);
        Contactpharmacybtn.setBorderPainted(false);
        Contactpharmacybtn.setContentAreaFilled(false);
        Contactpharmacybtn.addActionListener(this::ContactpharmacybtnActionPerformed);
        jPanel1.add(Contactpharmacybtn);
        Contactpharmacybtn.setBounds(560, 70, 132, 28);

        logopharmassist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reallogo.png"))); // NOI18N
        jPanel1.add(logopharmassist);
        logopharmassist.setBounds(10, 10, 40, 40);

        Accountbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounticon.png"))); // NOI18N
        Accountbtn.setText("Account");
        Accountbtn.setBorder(null);
        Accountbtn.setBorderPainted(false);
        Accountbtn.setContentAreaFilled(false);
        Accountbtn.addActionListener(this::AccountbtnActionPerformed);
        jPanel1.add(Accountbtn);
        Accountbtn.setBounds(620, 10, 80, 23);

        namepharmassist.setFont(new java.awt.Font("Comic Neue", 1, 20)); // NOI18N
        namepharmassist.setText("Pharm-Assist");
        jPanel1.add(namepharmassist);
        namepharmassist.setBounds(60, 3, 130, 40);

        Slogan.setFont(new java.awt.Font("Comic Neue", 0, 11)); // NOI18N
        Slogan.setText("Your healthy dose of convenience");
        jPanel1.add(Slogan);
        Slogan.setBounds(10, 50, 210, 13);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartlogo.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel1.add(jButton5);
        jButton5.setBounds(570, 10, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 100);

        contentPanel.setLayout(new java.awt.CardLayout());

        categories.setBackground(new java.awt.Color(244, 252, 255));
        categories.setLayout(null);

        categoryFilterPanel.setBackground(new java.awt.Color(255, 255, 255));
        categoryFilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        categoryFilterPanel.setLayout(null);

        PainReliefbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainReliefbtn.setText("Pain Relief");
        PainReliefbtn.addActionListener(this::PainReliefbtnActionPerformed);
        categoryFilterPanel.add(PainReliefbtn);
        PainReliefbtn.setBounds(0, 30, 120, 30);

        AntiFungalbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        AntiFungalbtn.setText("Antifungal");
        AntiFungalbtn.addActionListener(this::AntiFungalbtnActionPerformed);
        categoryFilterPanel.add(AntiFungalbtn);
        AntiFungalbtn.setBounds(0, 60, 120, 30);

        Allbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Allbtn.setText("All");
        Allbtn.addActionListener(this::AllbtnActionPerformed);
        categoryFilterPanel.add(Allbtn);
        Allbtn.setBounds(0, 0, 120, 30);

        categories.add(categoryFilterPanel);
        categoryFilterPanel.setBounds(30, 20, 120, 330);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        productScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        productListPanel.setBackground(new java.awt.Color(255, 255, 255));
        productScrollPane.setViewportView(productListPanel);

        jPanel3.add(productScrollPane);
        productScrollPane.setBounds(0, 0, 550, 330);

        categories.add(jPanel3);
        jPanel3.setBounds(150, 20, 530, 330);

        contentPanel.add(categories, "categories");

        emergency.setBackground(new java.awt.Color(255, 0, 0));
        contentPanel.add(emergency, "emergency");

        bmi.setBackground(new java.awt.Color(245, 253, 255));
        bmi.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(651, 319));
        jPanel14.setLayout(null);
        bmi.add(jPanel14);
        jPanel14.setBounds(30, 10, 651, 319);

        contentPanel.add(bmi, "bmi");

        pharmacy.setBackground(new java.awt.Color(244, 252, 255));
        pharmacy.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contact pharmacy1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 300);

        pharmacy.add(jPanel2);
        jPanel2.setBounds(30, 30, 640, 300);

        contentPanel.add(pharmacy, "pharmacy");

        ShoppingCart.setBackground(new java.awt.Color(244, 252, 255));
        ShoppingCart.setLayout(null);

        Selected.setBackground(new java.awt.Color(255, 255, 255));
        Selected.setLayout(null);

        checkbox1.setFont(new java.awt.Font("Comic Neue", 1, 10)); // NOI18N
        checkbox1.setLabel("SelectAll");
        Selected.add(checkbox1);
        checkbox1.setBounds(10, 0, 90, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        Selected.add(jButton1);
        jButton1.setBounds(280, 0, 20, 20);

        jLabel5.setFont(new java.awt.Font("Comic Neue", 1, 11)); // NOI18N
        jLabel5.setText("Delete Selected");
        Selected.add(jLabel5);
        jLabel5.setBounds(300, 0, 90, 20);

        ShoppingCart.add(Selected);
        Selected.setBounds(30, 50, 402, 24);

        OrderSummary.setBackground(new java.awt.Color(255, 255, 255));
        OrderSummary.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Comic Neue", 1, 12)); // NOI18N
        jLabel7.setText("Order Summary");
        OrderSummary.add(jLabel7);
        jLabel7.setBounds(10, 10, 150, 30);

        SelectedPrice.setBackground(new java.awt.Color(255, 255, 255));
        OrderSummary.add(SelectedPrice);
        SelectedPrice.setBounds(160, 50, 70, 20);

        TotalPriceAdd.setBackground(new java.awt.Color(255, 255, 255));
        OrderSummary.add(TotalPriceAdd);
        TotalPriceAdd.setBounds(160, 80, 70, 20);

        ConfirmPayment.setBackground(new java.awt.Color(14, 94, 174));
        ConfirmPayment.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPayment.setText("Confirm Cart");
        ConfirmPayment.addActionListener(this::ConfirmPaymentActionPerformed);
        OrderSummary.add(ConfirmPayment);
        ConfirmPayment.setBounds(35, 110, 160, 23);

        jLabel6.setText("Total Payment");
        OrderSummary.add(jLabel6);
        jLabel6.setBounds(10, 80, 130, 20);

        jLabel8.setText("Selected items price");
        OrderSummary.add(jLabel8);
        jLabel8.setBounds(10, 50, 130, 20);

        ShoppingCart.add(OrderSummary);
        OrderSummary.setBounds(460, 50, 230, 138);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);
        jPanel6.add(PictureOfMeds);
        PictureOfMeds.setBounds(10, 20, 50, 40);
        jPanel6.add(NameOfMeds);
        NameOfMeds.setBounds(70, 20, 80, 20);

        Quantity.setText("Quantity");
        jPanel6.add(Quantity);
        Quantity.setBounds(70, 40, 46, 16);

        ADD.setBackground(new java.awt.Color(14, 94, 174));
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("+");
        ADD.addActionListener(this::ADDActionPerformed);
        jPanel6.add(ADD);
        ADD.setBounds(120, 40, 20, 23);

        Subtract.setBackground(new java.awt.Color(14, 94, 174));
        Subtract.setForeground(new java.awt.Color(255, 255, 255));
        Subtract.setText("-");
        jPanel6.add(Subtract);
        Subtract.setBounds(180, 40, 20, 23);

        ShoppingCart.add(jPanel6);
        jPanel6.setBounds(30, 80, 402, 77);

        contentPanel.add(ShoppingCart, "cart");

        getContentPane().add(contentPanel);
        contentPanel.setBounds(0, 100, 700, 350);

        setBounds(0, 0, 716, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    private void AccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountbtnActionPerformed
        // TODO add your handling code here:
    jPopupMenu1.show(Accountbtn, 0, Accountbtn.getHeight());
    }//GEN-LAST:event_AccountbtnActionPerformed

    private void ContactpharmacybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactpharmacybtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) contentPanel.getLayout();
        card.show(contentPanel, "pharmacy");
    }//GEN-LAST:event_ContactpharmacybtnActionPerformed

    private void BmibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmibtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) contentPanel.getLayout();
        card.show(contentPanel, "bmi");
    }//GEN-LAST:event_BmibtnActionPerformed

    private void AllcategoriesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllcategoriesbtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) contentPanel.getLayout();
        card.show(contentPanel, "categories");
        
        
    }//GEN-LAST:event_AllcategoriesbtnActionPerformed

    private void EmergencycontactsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencycontactsbtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) contentPanel.getLayout();
        card.show(contentPanel, "emergency");
    }//GEN-LAST:event_EmergencycontactsbtnActionPerformed

    private void PainReliefbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PainReliefbtnActionPerformed
          currentCategory = "Pain Relief";
    loadProductsByCategory("Pain Relief");
    }//GEN-LAST:event_PainReliefbtnActionPerformed

    private void AntiFungalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntiFungalbtnActionPerformed
       currentCategory = "Anti-fungal";
    loadProductsByCategory("Anti-fungal");
    }//GEN-LAST:event_AntiFungalbtnActionPerformed

    private void AllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllbtnActionPerformed
        currentCategory = "All";
    loadAllProducts();   // TODO add your handling code here:
    }//GEN-LAST:event_AllbtnActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout card = (CardLayout) contentPanel.getLayout();
    card.show(contentPanel, "cart");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConfirmPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPaymentActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton Accountbtn;
    private javax.swing.JButton Allbtn;
    private javax.swing.JButton Allcategoriesbtn;
    private javax.swing.JButton AntiFungalbtn;
    private javax.swing.JButton Bmibtn;
    private javax.swing.JButton ConfirmPayment;
    private javax.swing.JButton Contactpharmacybtn;
    private javax.swing.JButton Emergencycontactsbtn;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JPanel NameOfMeds;
    private javax.swing.JPanel OrderSummary;
    private javax.swing.JButton PainReliefbtn;
    private javax.swing.JPanel PictureOfMeds;
    private javax.swing.JMenuItem Profile;
    private javax.swing.JLabel Quantity;
    private javax.swing.JMenuItem RateUs;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JPanel Selected;
    private javax.swing.JPanel SelectedPrice;
    private javax.swing.JPanel ShoppingCart;
    private javax.swing.JLabel Slogan;
    private javax.swing.JButton Subtract;
    private javax.swing.JPanel TotalPriceAdd;
    private javax.swing.JPanel bmi;
    private javax.swing.JPanel categories;
    private javax.swing.JPanel categoryFilterPanel;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel emergency;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel logopharmassist;
    private javax.swing.JLabel namepharmassist;
    private javax.swing.JPanel pharmacy;
    private javax.swing.JPanel productListPanel;
    private javax.swing.JScrollPane productScrollPane;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
public Controller.ShoppingCartController getCartController() {
    return cartController;
}


       private void performSearch() {
           
    String keyword = Searchbar.getText().trim();

    if (keyword.isEmpty()) {
        if ("All".equalsIgnoreCase(currentCategory)) loadAllProducts();
        else loadProductsByCategory(currentCategory);
        return;
    }

    productListPanel.removeAll();
    productListPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

    Model.SearchModel model = new Model.SearchModel(keyword, currentCategory);
    java.util.List<Model.Product> products = searchController.search(model);

    if (products.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No products found for: " + keyword);
    }

   for (Model.Product product : products) {
    ProductCard card = new ProductCard();
    card.setDashboard(this);          // 🔥 VERY IMPORTANT
    card.setProduct(product);
    card.setPreferredSize(new Dimension(150, 170));
    productListPanel.add(card);
}


    productListPanel.revalidate();
    productListPanel.repaint();
}
       // used by controller.plus/minus to know current qty shown
private java.util.Map<Integer, Integer> qtyMap = new java.util.HashMap<>();

public int getDisplayedQty(int productId) {
    return qtyMap.getOrDefault(productId, 1);
}

 public void renderCart(java.util.List<Model.CartItem> items) {

    jPanel6.removeAll();
    jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));
    qtyMap.clear();

    java.math.BigDecimal selectedTotal = java.math.BigDecimal.ZERO;

    for (Model.CartItem item : items) {
        qtyMap.put(item.getProductId(), item.getQuantity());

        view.CartRowPanel row = new view.CartRowPanel(cartController, item);
        jPanel6.add(row);

        if (item.isSelected()) {
            selectedTotal = selectedTotal.add(item.getLineTotal());
        }
    }

    selectedPriceLabel.setText("Rs. " + selectedTotal.toPlainString());
    totalPriceLabel.setText("Rs. " + selectedTotal.toPlainString());

    jPanel6.revalidate();
    jPanel6.repaint();
}



}
