/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author This PC
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        addressTextArea = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        nameLabel.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        nameLabel.setText("Full Name");
        add(nameLabel);
        nameLabel.setBounds(20, 50, 70, 14);

        contactLabel.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        contactLabel.setText("Contact Number");
        add(contactLabel);
        contactLabel.setBounds(20, 100, 100, 14);

        addressLabel.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        addressLabel.setText("Address");
        add(addressLabel);
        addressLabel.setBounds(20, 150, 70, 14);

        nameTextField.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        nameTextField.addActionListener(this::nameTextFieldActionPerformed);
        add(nameTextField);
        nameTextField.setBounds(20, 70, 200, 30);

        contactTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(contactTextField);
        contactTextField.setBounds(20, 120, 200, 30);

        addressTextArea.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        add(addressTextArea);
        addressTextArea.setBounds(20, 170, 200, 50);

        cancelButton.setBackground(new java.awt.Color(239, 79, 79));
        cancelButton.setFont(new java.awt.Font("Comic Neue", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        add(cancelButton);
        cancelButton.setBounds(30, 250, 72, 21);

        saveButton.setBackground(new java.awt.Color(14, 93, 174));
        saveButton.setFont(new java.awt.Font("Comic Neue", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);
        add(saveButton);
        saveButton.setBounds(150, 250, 72, 21);

        lbltitle.setFont(new java.awt.Font("Comic Neue", 1, 16)); // NOI18N
        lbltitle.setText("New Shipping Address");
        add(lbltitle);
        lbltitle.setBounds(29, 7, 173, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
