/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ForgotPasswordController;
import javax.swing.JOptionPane;

/**
 *
 * @author kritss
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());
private final ForgotPasswordController controller = new ForgotPasswordController();

    /**
     * Creates new form ForgotPassword
     */
public ForgotPassword() {
        initComponents();
     
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pharmassist = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bmi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pCONTACTS = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        categories = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Forgot = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSendOtp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOtp = new javax.swing.JTextField();
        btnVerifyOtp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        btnResetPassword = new javax.swing.JButton();
        backgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(700, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));
        jPanel1.setLayout(null);

        Pharmassist.setFont(new java.awt.Font("Comic Neue", 0, 20)); // NOI18N
        Pharmassist.setText("Pharm-Assist");
        jPanel1.add(Pharmassist);
        Pharmassist.setBounds(50, 10, 160, 23);

        Slogan.setFont(new java.awt.Font("Comic Neue", 0, 11)); // NOI18N
        Slogan.setText("Your healthy dose of convenience ");
        jPanel1.add(Slogan);
        Slogan.setBounds(0, 50, 180, 13);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        jLabel1.setText("Emergency Contacts");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(180, 70, 130, 20);

        Bmi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        jLabel2.setText("BMI");

        javax.swing.GroupLayout BmiLayout = new javax.swing.GroupLayout(Bmi);
        Bmi.setLayout(BmiLayout);
        BmiLayout.setHorizontalGroup(
            BmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        BmiLayout.setVerticalGroup(
            BmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(Bmi);
        Bmi.setBounds(370, 70, 90, 20);

        pCONTACTS.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        pCONTACTS.setText("Contact Pharmacy");
        jPanel1.add(pCONTACTS);
        pCONTACTS.setBounds(590, 60, 110, 40);

        jPanel3.setBackground(new java.awt.Color(14, 93, 174));

        categories.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        categories.setForeground(new java.awt.Color(255, 255, 255));
        categories.setText("All Categories");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(categories))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 70, 120, 20);

        Account.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        Account.setText("Account");
        jPanel1.add(Account);
        Account.setBounds(640, 20, 50, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        Forgot.setFont(new java.awt.Font("Comic Neue", 1, 20)); // NOI18N
        Forgot.setText("Forgot your Password?");
        jPanel4.add(Forgot);
        Forgot.setBounds(6, 0, 239, 30);

        edit.setFont(new java.awt.Font("Comic Neue", 0, 18)); // NOI18N
        edit.setText("E-mail");
        jPanel4.add(edit);
        edit.setBounds(10, 40, 250, 20);

        txtEmail.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        txtEmail.setText("Enter your email");
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        jPanel4.add(txtEmail);
        txtEmail.setBounds(10, 70, 290, 30);

        btnSendOtp.setBackground(new java.awt.Color(14, 93, 174));
        btnSendOtp.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        btnSendOtp.setForeground(new java.awt.Color(255, 255, 255));
        btnSendOtp.setText("Send OTP");
        btnSendOtp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSendOtp.addActionListener(this::btnSendOtpActionPerformed);
        jPanel4.add(btnSendOtp);
        btnSendOtp.setBounds(260, 110, 90, 25);

        jLabel3.setFont(new java.awt.Font("Comic Neue", 0, 18)); // NOI18N
        jLabel3.setText("OTP");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 130, 50, 22);

        txtOtp.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        txtOtp.setText("Enter the OTP");
        txtOtp.addActionListener(this::txtOtpActionPerformed);
        jPanel4.add(txtOtp);
        txtOtp.setBounds(10, 160, 280, 20);

        btnVerifyOtp.setBackground(new java.awt.Color(14, 93, 174));
        btnVerifyOtp.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        btnVerifyOtp.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyOtp.setText("Verify");
        btnVerifyOtp.setPreferredSize(new java.awt.Dimension(56, 20));
        btnVerifyOtp.addActionListener(this::btnVerifyOtpActionPerformed);
        jPanel4.add(btnVerifyOtp);
        btnVerifyOtp.setBounds(260, 190, 90, 20);

        jLabel4.setFont(new java.awt.Font("Comic Neue", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 220, 110, 30);

        txtNewPassword.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        txtNewPassword.setText("Enter your new password");
        txtNewPassword.addActionListener(this::txtNewPasswordActionPerformed);
        jPanel4.add(txtNewPassword);
        txtNewPassword.setBounds(10, 250, 280, 20);

        btnResetPassword.setBackground(new java.awt.Color(14, 97, 174));
        btnResetPassword.setFont(new java.awt.Font("Comic Neue", 1, 13)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPassword.setText("Reset");
        btnResetPassword.addActionListener(this::btnResetPasswordActionPerformed);
        jPanel4.add(btnResetPassword);
        btnResetPassword.setBounds(260, 280, 100, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(120, 110, 470, 320);

        backgroundimage.setBackground(new java.awt.Color(255, 255, 255));
        backgroundimage.setForeground(new java.awt.Color(255, 255, 255));
        backgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot (3).png"))); // NOI18N
        backgroundimage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundimage.setPreferredSize(new java.awt.Dimension(700, 450));
        jPanel1.add(backgroundimage);
        backgroundimage.setBounds(0, 0, 710, 456);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 731, 447);

        setBounds(0, 0, 722, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOtpActionPerformed
        // TODO add your handling code here:
        
        
String email = txtEmail.getText();
    if (controller.sendOtp(email)) {
        JOptionPane.showMessageDialog(this, "OTP sent to email");
    } else {
        JOptionPane.showMessageDialog(this, "Email not found");
    }
       
    }//GEN-LAST:event_btnSendOtpActionPerformed

    private void txtOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtpActionPerformed

    private void btnVerifyOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyOtpActionPerformed
        // TODO add your handling code here:
         if (controller.verifyOtp(txtOtp.getText())) {
        JOptionPane.showMessageDialog(this, "OTP Verified");
    } else {
        JOptionPane.showMessageDialog(this, "Invalid OTP");
    }

    }//GEN-LAST:event_btnVerifyOtpActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        // TODO add your handling code here:
         boolean success = controller.resetPassword(
        txtEmail.getText(),
        txtNewPassword.getText()
    );

    if (success) {
        JOptionPane.showMessageDialog(this, "Password reset successful!");
    } else {
        JOptionPane.showMessageDialog(this, "Please verify OTP first!");
    }

    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JPanel Bmi;
    private javax.swing.JLabel Forgot;
    private javax.swing.JLabel Pharmassist;
    private javax.swing.JLabel Slogan;
    private javax.swing.JLabel backgroundimage;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JButton btnSendOtp;
    private javax.swing.JButton btnVerifyOtp;
    private javax.swing.JLabel categories;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel pCONTACTS;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtOtp;
    // End of variables declaration//GEN-END:variables
}
