/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Controller.UserController;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author This PC
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Login.class.getName());

    private UserController controller = new UserController();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtUsername.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        jPanel2.add(txtUsername);
        txtUsername.setBounds(30, 30, 370, 40);

        Email.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        Email.setText("Email");
        jPanel2.add(Email);
        Email.setBounds(30, 10, 60, 17);

        password.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        password.setText("Password");
        jPanel2.add(password);
        password.setBounds(30, 86, 100, 20);

        jLabel5.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        jLabel5.setText("Not a member? Sign Up Now");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 210, 190, 30);

        jLabel4.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        jLabel4.setText("Forgot Password?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(300, 160, 110, 20);

        txtPassword.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(30, 110, 370, 40);

        btnLogin.setBackground(new java.awt.Color(14, 94, 174));
        btnLogin.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        jPanel2.add(btnLogin);
        btnLogin.setBounds(170, 170, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 150, 427, 248);

        welcome.setFont(new java.awt.Font("Comic Neue", 1, 20)); // NOI18N
        welcome.setText("Welcome back to Pharm-Assist");
        jPanel1.add(welcome);
        welcome.setBounds(190, 130, 350, 20);

        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(backgroundimg);
        backgroundimg.setBounds(0, -10, 710, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 450);

        setBounds(0, 0, 716, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Get input from text fields
     String username = txtUsername.getText();
    String password = new String(txtPassword.getPassword());

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username/email and password");
        return;
    }

    dao.UserDAO userDAO = new dao.UserDAO();
    Model.User user = controller.login(username, password);

    if (user != null) {
        JOptionPane.showMessageDialog(this, "Login Successful!");
        
        System.out.println("=== Login Successful ===");
        System.out.println("User ID: " + user.getId());
        System.out.println("Username: " + user.getUsername());
        System.out.println("Address: " + user.getAddress());

        if ("ADMIN".equalsIgnoreCase(user.getRole())) {
            AdminDashboard adminDash = new AdminDashboard();
            adminDash.setVisible(true);
        } else {
            // Create Dashboard WITHOUT parameter
            Dashboard userDash = new Dashboard();  // Use default constructor
            userDash.setCurrentUser(user);         // Then set the user
            userDash.setVisible(true);
        }

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username/email or password");
    }



    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new ForgotPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
