/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author kritss
 */

import javax.swing.*;
import java.awt.event.ActionListener;

public class PaymentMethodPanel extends javax.swing.JPanel {
   
    public PaymentMethodPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TEXT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        Stripe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cod = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        TEXT.setFont(new java.awt.Font("Comic Neue", 1, 18)); // NOI18N
        TEXT.setText("Select Payment Method");
        add(TEXT);
        TEXT.setBounds(160, 10, 200, 50);

        jLabel1.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        jLabel1.setText("Stripe");
        add(jLabel1);
        jLabel1.setBounds(60, 190, 60, 14);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/payyy.png"))); // NOI18N
        add(image);
        image.setBounds(50, 120, 70, 60);

        Stripe.addActionListener(this::StripeActionPerformed);
        add(Stripe);
        Stripe.setBounds(20, 90, 130, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/CODed.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(400, 110, 70, 60);

        jLabel3.setText("COD");
        add(jLabel3);
        jLabel3.setBounds(420, 190, 30, 16);

        Cod.addActionListener(this::CodActionPerformed);
        add(Cod);
        Cod.setBounds(370, 90, 130, 120);
    }// </editor-fold>//GEN-END:initComponents

    private void StripeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StripeActionPerformed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_StripeActionPerformed

    private void CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cod;
    private javax.swing.JButton Stripe;
    private javax.swing.JLabel TEXT;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables


// -------------------------------
// Listener setters for Dashboard
// -------------------------------

// ---- Listener helpers (safe, ma'am approved) ----
public void addStripeListener(ActionListener l) {
    Stripe.addActionListener(l);
}

public void addCODListener(ActionListener l) {
    Cod.addActionListener(l);
}

}