/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import Controller.PaymentController;


/**
 *
 * @author kritss
 */
public class PaymentMethodPanel extends javax.swing.JPanel {

    public interface PaymentSelectionListener {
    void stripeSelected();
    void codSelected();
}
    /**
     * Creates new form PaymentMethodPanel
     */
    private final PaymentSelectionListener listener; // reference to listener

    /**
     * Constructor with listener
     * @param listener
     */
    public PaymentMethodPanel() {
    this.listener = null;
    initComponents();
    }
    public PaymentMethodPanel(PaymentSelectionListener listener) {
        this.listener = listener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        stripeimage = new javax.swing.JLabel();
        codimage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Stripe = new javax.swing.JButton();
        COD = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Neue", 1, 18)); // NOI18N
        jLabel1.setText("Select Payment Method");
        add(jLabel1);
        jLabel1.setBounds(140, 20, 260, 40);

        stripeimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay.jpeg"))); // NOI18N
        add(stripeimage);
        stripeimage.setBounds(47, 100, 70, 70);

        codimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cod.jpeg"))); // NOI18N
        add(codimage);
        codimage.setBounds(340, 100, 70, 70);

        jLabel2.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        jLabel2.setText("Stripe");
        add(jLabel2);
        jLabel2.setBounds(60, 180, 37, 16);

        jLabel3.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        jLabel3.setText("COD");
        add(jLabel3);
        jLabel3.setBounds(360, 180, 23, 20);

        Stripe.addActionListener(this::StripeActionPerformed);
        add(Stripe);
        Stripe.setBounds(20, 90, 120, 120);

        COD.addActionListener(this::CODActionPerformed);
        add(COD);
        COD.setBounds(310, 90, 120, 120);
    }// </editor-fold>//GEN-END:initComponents

    private void StripeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StripeActionPerformed
  PaymentController paymentController = new PaymentController();
    paymentController.handleStripeSelection(listener);
    }//GEN-LAST:event_StripeActionPerformed

    private void CODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODActionPerformed
    PaymentController paymentController = new PaymentController();
    paymentController.handleCodSelection(listener);
    }//GEN-LAST:event_CODActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COD;
    private javax.swing.JButton Stripe;
    private javax.swing.JLabel codimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel stripeimage;
    // End of variables declaration//GEN-END:variables
}
