/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Controller.ProductDetailsController;
import Model.Productdetails;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

public class ProductDescriptionPanel extends javax.swing.JPanel {

    private final int productId;
    private final ProductDetailsController Controller;
    private final JPanel parentPanel;// reference to Dashboard's contentPanel
    private final javax.swing.JLabel lblImage;


    public ProductDescriptionPanel(int productId, JPanel parentPanel) {
        this.productId = productId;
        this.Controller = new ProductDetailsController();
        this.parentPanel = parentPanel; // store reference
        initComponents();   // NetBeans-generated init
        lblImage = new javax.swing.JLabel();
lblImage.setBounds(10, 10, 180, 180); // adjust size and position
lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
lblImage.setOpaque(true);
lblImage.setBackground(Color.WHITE);
add(lblImage);

        
          txtDescription.setLineWrap(true);
    txtDescription.setWrapStyleWord(true);
    jScrollPane1.setVerticalScrollBarPolicy(
            javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
    );
    // Optional: increase visible height
    jScrollPane1.setBounds(
            jScrollPane1.getX(),
            jScrollPane1.getY(),
            jScrollPane1.getWidth(),
            150 // adjust height as needed
    );
        loadProduct();      // load product info
       
        
     Back.addActionListener(e -> {
            CardLayout cl = (CardLayout) parentPanel.getLayout();
            cl.show(parentPanel, "categories"); // Go back to product list
        });
    }

    private void loadProduct() {
        Productdetails product = Controller.getProductDetails(productId);

        if (product != null) {
            Name.setText(product.getName());
            Price.setText("Rs. " + product.getPrice());
            txtDescription.setText(product.getDescription());
            loadProductImage(product.getImage());
        
        } else {
            Name.setText("Product not found");
            Price.setText("");
            txtDescription.setText("No description available");
             lblImage.setText("No Image");
        lblImage.setIcon(null);
        }

        txtDescription.setLineWrap(true);
        txtDescription.setWrapStyleWord(true);
    }
    
    
private void loadProductImage(String imageName) {
    if (imageName == null || imageName.isEmpty()) {
        lblImage.setText("No Image");
        lblImage.setIcon(null);
        return;
    }

    try {
        // Load from src/images folder directly
        ImageIcon icon = new ImageIcon("src/images/" + imageName);
        Image img = icon.getImage();
        Image scaledImg = scaleImageToFit(img, lblImage.getWidth(), lblImage.getHeight());
        lblImage.setIcon(new ImageIcon(scaledImg));
        lblImage.setText("");
    } catch (Exception e) {
        lblImage.setText("No Image");
        lblImage.setIcon(null);
    }
}

private Image scaleImageToFit(Image img, int width, int height) {
    int originalWidth = img.getWidth(null);
    int originalHeight = img.getHeight(null);
    double ratio = Math.min((double) width / originalWidth, (double) height / originalHeight);
    int newWidth = (int) (originalWidth * ratio);
    int newHeight = (int) (originalHeight * ratio);
    return img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
}


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(575, 450));
        setLayout(null);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 175, 146);

        Name.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        Name.setText("jLabel1");
        add(Name);
        Name.setBounds(210, 10, 140, 17);

        Price.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        Price.setText("jLabel3");
        add(Price);
        Price.setBounds(210, 30, 110, 17);

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 670, 200);

        Back.setFont(new java.awt.Font("Comic Neue", 1, 12)); // NOI18N
        Back.setText("Go Back");
        add(Back);
        Back.setBounds(583, 120, 80, 21);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables

}