package view;

import Controller.ProductDetailsController;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Color;

public class ProductDescriptionPanel extends javax.swing.JPanel {
    private final int productId;
    private final ProductDetailsController controller;
    private final JPanel parentPanel;
    private final javax.swing.JLabel lblImage;  

    public ProductDescriptionPanel(int productId, JPanel parentPanel) {
        this.productId = productId;
        this.controller = new ProductDetailsController();
        this.parentPanel = parentPanel;
        initComponents();
        
       
        lblImage = new javax.swing.JLabel();
        lblImage.setBounds(10, 10, 180, 180);
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);
        lblImage.setBackground(Color.WHITE);
        lblImage.setBorder(
            javax.swing.BorderFactory.createLineBorder(Color.GRAY)
        );
        add(lblImage);
        
        
        txtDescription.setLineWrap(true);
        txtDescription.setWrapStyleWord(true);
        
       
        controller.loadAndDisplayProduct(productId, Name, Price, txtDescription, lblImage);
        
        
        Back.addActionListener(e -> {
            CardLayout cl = (CardLayout) parentPanel.getLayout();
            cl.show(parentPanel, "categories");
        });
    }
     


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(575, 450));
        setLayout(null);

        Name.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        Name.setText("jLabel1");
        add(Name);
        Name.setBounds(210, 10, 140, 17);

        Price.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        Price.setText("jLabel3");
        add(Price);
        Price.setBounds(210, 30, 110, 17);

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 670, 200);

        Back.setFont(new java.awt.Font("Comic Neue", 1, 12)); // NOI18N
        Back.setText("Go Back");
        add(Back);
        Back.setBounds(583, 120, 80, 21);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables

}