/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

import Model.Product;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author This PC
 */
public class ProductCard extends javax.swing.JPanel {
    
    
    private Product product;
    
    
    
    
    /**
     * Creates new form product
     */
    public ProductCard() {
    initComponents();
    lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    
}

        // Set the product data
    public void setProduct(Product product) {
        this.product = product;
        if (product != null) {
            // Set name and price
            lblName.setText(product.getName());
            lblPrice.setText("Rs." + product.getPrice());
            
            // Load the image
            loadProductImage();
        }
    }
    
    // Get the product

    
    
    
    public void setCartButtonAction(java.awt.event.ActionListener listener) {
        btnAddToCart.addActionListener(listener);
    }
    
    

    // Load product image
    private void loadProductImage() {
        if (product == null) {
        lblImage.setText("No Image");
        lblImage.setIcon(null);
        return;
    }
    
    String imageName = product.getImage();
    if (imageName == null || imageName.isEmpty()) {
        lblImage.setText("No Image");
        lblImage.setIcon(null);
        return;
    }
    
    try {
        // Try to load from /images folder
        java.net.URL imageUrl = getClass().getResource("/images/" + imageName);
        
        if (imageUrl != null) {
            ImageIcon icon = new ImageIcon(imageUrl);
            Image image = icon.getImage();
            
            // SCALE TO FIT 60x60 while keeping aspect ratio
            Image scaledImage = scaleImageToFit(image, 60, 60);
            
            lblImage.setIcon(new ImageIcon(scaledImage));
            lblImage.setText(""); // Clear text
        } else {
            // Image not found
            lblImage.setText("No Image");
            lblImage.setIcon(null);
        }
    } catch (Exception e) {
        // If any error occurs
        lblImage.setText("No Image");
        lblImage.setIcon(null);
    }
}
    
    

// ADD THIS NEW METHOD right after loadProductImage()
private Image scaleImageToFit(Image img, int width, int height) {
    int originalWidth = img.getWidth(null);
    int originalHeight = img.getHeight(null);
    
    // Calculate scaling ratio
    double widthRatio = (double) width / originalWidth;
    double heightRatio = (double) height / originalHeight;
    double ratio = Math.min(widthRatio, heightRatio);
    
    // Calculate new dimensions
    int newWidth = (int) (originalWidth * ratio);
    int newHeight = (int) (originalHeight * ratio);
    
    // Scale image
    return img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
       

            
    
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   // </editor-fold>                        

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(null);

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setOpaque(true);
        add(lblImage);
        lblImage.setBounds(50, 10, 60, 60);

        lblName.setText("     item name");
        add(lblName);
        lblName.setBounds(20, 80, 110, 20);

        lblPrice.setText("     item price");
        add(lblPrice);
        lblPrice.setBounds(20, 100, 110, 20);

        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAddToCart.setText("Add to cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);
        add(btnAddToCart);
        btnAddToCart.setBounds(30, 130, 100, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
          if (product != null) {
            JOptionPane.showMessageDialog(this, 
                "Added to cart: " + product.getName() + 
                "\nPrice: Rs." + product.getPrice());
        }// TODO add your handling code here:
                                                
    
    
    }//GEN-LAST:event_btnAddToCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    // End of variables declaration//GEN-END:variables

}

