/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Controller.SignupController;
import Model.User;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


/**
 *
 * @author LOQ
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        txtpasword = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        lblpasswords = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        btnregester = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 450));

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtname.addActionListener(this::txtnameActionPerformed);
        jPanel1.add(txtname);
        txtname.setBounds(20, 90, 230, 30);

        txtpasword.addActionListener(this::txtpaswordActionPerformed);
        jPanel1.add(txtpasword);
        txtpasword.setBounds(330, 90, 220, 30);

        lblname.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        lblname.setText("User Name");
        jPanel1.add(lblname);
        lblname.setBounds(20, 70, 90, 16);

        lblpasswords.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        lblpasswords.setText("Password");
        jPanel1.add(lblpasswords);
        lblpasswords.setBounds(330, 70, 140, 20);

        lblemail.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        lblemail.setText("Email");
        jPanel1.add(lblemail);
        lblemail.setBounds(20, 130, 120, 16);

        txtemail.addActionListener(this::txtemailActionPerformed);
        jPanel1.add(txtemail);
        txtemail.setBounds(20, 150, 230, 30);

        lblphoneno.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        lblphoneno.setText("Phone No");
        jPanel1.add(lblphoneno);
        lblphoneno.setBounds(330, 130, 170, 20);
        jPanel1.add(txtphoneno);
        txtphoneno.setBounds(330, 150, 230, 30);

        btnregester.setText("Register");
        btnregester.addActionListener(this::btnregesterActionPerformed);
        jPanel1.add(btnregester);
        btnregester.setBounds(540, 250, 100, 23);

        jLabel7.setFont(new java.awt.Font("Comic Neue", 1, 14)); // NOI18N
        jLabel7.setText("Yours Personal Details");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 160, 30);

        lbladdress.setFont(new java.awt.Font("Comic Neue", 0, 13)); // NOI18N
        lbladdress.setText("Address");
        jPanel1.add(lbladdress);
        lbladdress.setBounds(20, 190, 90, 16);

        txtaddress.addActionListener(this::txtaddressActionPerformed);
        jPanel1.add(txtaddress);
        txtaddress.setBounds(20, 210, 310, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 130, 690, 300);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 450);

        setBounds(0, 0, 714, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtpaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaswordActionPerformed

    private void btnregesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregesterActionPerformed
        // TODO add your handling code here:
       // Get values from the form fields
    String username = txtname.getText().trim();
    String password = txtpasword.getText().trim();  // Plain password
    String email = txtemail.getText().trim();
    String phoneNumber = txtphoneno.getText().trim();
    String address = txtaddress.getText().trim();

    // Simple validation to make sure no fields are empty
    if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phoneNumber.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields must be filled!", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;  // Stop the execution if validation fails
    }

    // Create a User object with the data
    User user = new User(username, email, password, phoneNumber, address, "USER");

    // Create the SignupController to handle registration
    SignupController controller = new SignupController();
    String resultMessage = controller.register(user);  // Call the register method from the controller

    // Display the result message
    JOptionPane.showMessageDialog(this, resultMessage);

    // If registration is successful, clear the fields
    if ("Registration successful!".equals(resultMessage)) {
        clearFields();
    }
}

// Helper method to clear the fields after successful registration
private void clearFields() {
    txtname.setText("");
    txtpasword.setText("");
    txtemail.setText("");
    txtphoneno.setText("");
    txtaddress.setText("");
  

    }//GEN-LAST:event_btnregesterActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregester;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpasswords;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpasword;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables
}
