/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author LOQ
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(700, 450));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Your Personal Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 263, 20);

        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 108, 24);

        jLabel6.setText("First name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 70, 68, 16);

        jLabel7.setText("Last name:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 70, 73, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 90, 182, 22);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 90, 196, 22);

        jLabel8.setText("Date of birth:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 70, 100, 16);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(580, 227, 88, 22);

        jLabel13.setText("Email:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 120, 76, 16);

        jLabel14.setText("Phone:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(210, 120, 75, 20);

        jLabel15.setText("Your Address:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 160, 126, 20);

        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(10, 140, 182, 22);

        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 140, 200, 22);

        jLabel16.setText("Municiplity:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 180, 90, 16);

        jLabel17.setText("Ward no:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(210, 180, 96, 16);

        jLabel18.setText("Area:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 180, 60, 16);

        jTextField5.addActionListener(this::jTextField5ActionPerformed);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(10, 200, 180, 22);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(210, 200, 200, 22);

        jTextField7.addActionListener(this::jTextField7ActionPerformed);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(470, 200, 145, 22);

        jLabel19.setText("Your password");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 220, 98, 20);

        jLabel20.setText("Confirm password:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(210, 240, 109, 16);

        jLabel21.setText("Password:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 240, 90, 16);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(10, 260, 180, 22);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(210, 260, 200, 22);

        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 290, 110, 23);

        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(30, 40, 49, 21);

        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(120, 40, 61, 21);

        jTextField10.addActionListener(this::jTextField10ActionPerformed);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(470, 90, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 690, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -4, 700, 460);

        setBounds(0, 0, 714, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
