/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author kritss
 */
public class StripePayPanel extends javax.swing.JPanel {

    /**
     * Creates new form StripePayPanel
     */
    public StripePayPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textOnlinePayment = new javax.swing.JLabel();
        warningmessage = new javax.swing.JLabel();
        PayNow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        textOnlinePayment.setFont(new java.awt.Font("Comic Neue", 1, 18)); // NOI18N
        textOnlinePayment.setText("Online Payment Stripe");
        add(textOnlinePayment);
        textOnlinePayment.setBounds(90, 10, 190, 40);

        warningmessage.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        warningmessage.setText("You will be redirected to  Stripe secure payment page ");
        add(warningmessage);
        warningmessage.setBounds(20, 140, 320, 40);

        PayNow.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        PayNow.setText("[ Pay Now ]");
        add(PayNow);
        PayNow.setBounds(20, 190, 100, 21);

        jButton1.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        jButton1.setText("[ Cancel ]");
        add(jButton1);
        jButton1.setBounds(235, 190, 90, 20);

        jLabel1.setFont(new java.awt.Font("Comic Neue", 0, 12)); // NOI18N
        jLabel1.setText("Total Amount: Rs. XXXX");
        add(jLabel1);
        jLabel1.setBounds(20, 80, 270, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PayNow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textOnlinePayment;
    private javax.swing.JLabel warningmessage;
    // End of variables declaration//GEN-END:variables
}
