/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import Controller.PaymentController;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class StripePaymentPanel extends javax.swing.JPanel {
    private final JPanel parentPanel;
    private final double totalAmount;
    
    // Constructor - add totalAmount parameter
    public StripePaymentPanel(JPanel parentPanel, double totalAmount) {
        this.parentPanel = parentPanel;
        this.totalAmount = totalAmount;
        initComponents();
        
        // Set the total
        jLabel3.setText("Total Amount : Rs " + totalAmount);
        
        // Add action listeners AFTER initComponents()
        setupListeners();
    }
    
    // Update this method in setupListeners()
private void setupListeners() {
    // Cancel button navigates back
    jButton2.addActionListener(e -> {
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "categories");
    });
    
    // Pay Now button - calls controller
    jButton1.addActionListener(e -> {
        PaymentController paymentController = new PaymentController();
        paymentController.processStripePayment(parentPanel, jButton1, totalAmount);
    });
}
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Neue", 1, 18)); // NOI18N
        jLabel1.setText("Online Payment Stripe");
        add(jLabel1);
        jLabel1.setBounds(84, 17, 230, 30);

        jLabel2.setFont(new java.awt.Font("Comic Neue", 0, 16)); // NOI18N
        jLabel2.setText("Proceed to payment via Stripe.");
        add(jLabel2);
        jLabel2.setBounds(30, 150, 350, 30);

        jButton1.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        jButton1.setText("[ Pay Now ]");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        add(jButton1);
        jButton1.setBounds(20, 210, 110, 24);

        jButton2.setFont(new java.awt.Font("Comic Neue", 0, 14)); // NOI18N
        jButton2.setText("[ Cancel ]");
        add(jButton2);
        jButton2.setBounds(270, 210, 100, 24);

        jLabel3.setFont(new java.awt.Font("Comic Neue", 0, 16)); // NOI18N
        jLabel3.setText("Total Amount : Rs XXXX");
        add(jLabel3);
        jLabel3.setBounds(30, 110, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PaymentController paymentController = new PaymentController();
    paymentController.processStripePayment(parentPanel, jButton1, totalAmount);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

   
}
